### ISSUE TITLE
Error: no_text

### ISSUE THREAD

**Issue by KambingLandia** [PandarusAnon/slaude#13]
Why do some of the chars generate stuff like:

Error: no_text
    at postSlackMessage (file:///D:/KambingSaja/Application/slaude/app.js:428:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createSlackThread (file:///D:/KambingSaja/Application/slaude/app.js:439:12)
    at async file:///D:/KambingSaja/Application/slaude/app.js:54:24
Error: no_text
    at postSlackMessage (file:///D:/kambingSaja/Application/slaude/app.js:428:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createSlackThread (file:///D:/KambingSaja/Application/slaude/app.js:439:12)
    at async file:///D:/KambingSajaApplication/slaude/app.js:54:24

**Comment by KambingLandia** [comment]
It seems like VPN are causing this problems, i can just turn it off to solve this problem. Too bad though.

**Comment by ydrk12** [comment]
I was not using a VPN, however I still have the problem, someone with the same problems?

**Comment by ydrk12** [comment]
It seems to be a bug
