### ISSUE TITLE
help

### ISSUE THREAD

**Issue by oEjk** [PandarusAnon/slaude#6]
Error: no_text
    at postSlackMessage (file:/slaude/app.js:428:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createSlackThread (file:/slaude/app.js:439:12)
    at async file:/slaude/app.js:54:24
    
Just pulled today.
double checked config.

**Comment by PandarusAnon** [comment]
This might be two weeks old but I'd still like to at least address it. As the error message implies, Slaude tried to create the original thread message with no contents. That could have a number of reasons but to say for sure I'd need to know what exactly your config settings were (not your Slack specific settings, just the Slaude stuff like MAINPROMPT_LAST and PING_MESSAGE as well as the prompt you were using at the time. My guess would be that a combination of your config and the prompt caused the first message we wanted to send to Slack to just be an empty string. I'm just not sure how we would've gotten there since all messages are put together by combining the individual OpenAI formatted messages until we exceed the character limit. But without knowing exactly what you prompted and which settings you used guessing is all I can do.

Of course this is two weeks old and you might not be comfortable with sharing what you were prompting so I'm not expecting you to actually do this, I'm just saying that's the only way I can pin this down and I don't really have the time to try and reproduce bugs with pure trial and error anymore.
